_BASE_: "/home/tbelldev/workspace/autoLabeling/api_test/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
MODEL:
  WEIGHTS: "/home/tbelldev/workspace/autoLabeling/api_test/pkl/model_final_f10217.pkl"